server:
  address: 0.0.0.0  # 绑定所有 IPv4 接口
  port: 8432 # 可选：指定端口

pagehelper:
  # 设置方言，此处指定 MySQL 数据库
  helper-dialect: mysql
  # 是否启动合理化，默认是 false。
  # 启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages（最大页数）会查询最后一页。
  # 禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
  reasonable: true
  # 是否支持接口参数来传递分页参数，默认false
  support-methods-arguments: true
  # 为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值
  params: count=countSql
  # 默认值为 false，当该参数设置为 true 时，如果 pageSize=0 或者 RowBounds.limit = 0 就会查询出全部的结果（相当于没有执行分页查询，但是返回结果仍然是 Page 类型）
  page-size-zero: true
mybatis:
  mapper-locations: classpath:com/xy/mapper/*.xml
  type-aliases-package: com.xy.pojo
  configuration:  # setting配置
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
#    lazy-loading-enabled : true
#    aggressive-lazy-loading : false
#    log-impl : org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  servlet:
    multipart:
      enabled=true
      max-file-size=10MB
      max-request-size=10MB
  datasource:
    url: jdbc:mysql://47.117.34.210:3306/agri
    username: aguser
    password: sc201@dzxy
    driver-class-name: com.mysql.cj.jdbc.Driver
coze:
  api:
    key: "pat_kZil4YxslIjzrI0GwzKy3y6MGHkE5qMjmBNUAAryoUGUveufZVAaxIpdBj7wUxfs"
    bot-id: "7490911192907546636"
    base-url: "https://api.coze.cn/v3/chat"
deepseek:
  api:
    key: "sk-defde54bc2d64ffda55a1592b6bf4c67"
    base-url: "https://api.deepseek.com"
    model: "deepseek-chat"
    temperature: 0.7
    max-tokens: 2000